# Stage 1: Build the Angular application
FROM node:20 AS build

# Set the working directory
WORKDIR /app

# Copy the Angular project files
COPY vimar-frontend/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY ./vimar-frontend/ ./

# Build the Angular application for production
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy a custom Nginx configuration file
COPY config/nginx/nginx.conf /etc/nginx/conf.d/

# Copy the build output to Nginx's HTML folder
COPY --from=build /app/dist/vimar-frontend/browser/ /usr/share/nginx/html

# Expose the port Nginx runs on
EXPOSE 4200

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
